ALTER TABLE `abastecimentosDiesel` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `alertasFinanceiros` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `anexosFinanceiros` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `baixasFinanceiras` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `bitolas` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `categoriasFinanceiras` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `clientes` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `configuracoesFinanceiras` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `contasFinanceiras` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `empresaConfiguracoes` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `extratosBancarios` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `fornecedores` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `historicoAlteracoes` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `itensOrcamento` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `itensRomaneioProducao` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `itensRomaneioToras` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `lotesPecasSerradas` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `madeiras` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `modelosMedidaVenda` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `movimentacoesEstoqueSerrado` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `movimentacoesPlaquetas` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `movimentosExtratoBancario` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `notasDiesel` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `orcamentos` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `plaquetas` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `recorrenciasFinanceiras` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `romaneiosCargaToras` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `romaneiosProducao` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `sequenciasVendas` MODIFY COLUMN `empresaId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `titulosFinanceiros` MODIFY COLUMN `empresaId` int NOT NULL;