import { AlertTriangle, ArrowLeft, ClipboardCheck, FileWarning, Search, TreePine } from "lucide-react";
import { Link } from "wouter";
import { etiquetaPlaqueta } from "@shared/plaquetas";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useState } from "react";

const formatarNumero = (valor: number | string, casas = 3) => new Intl.NumberFormat("pt-BR", { maximumFractionDigits: casas }).format(Number(valor ?? 0));
const formatarData = (valor: string | Date) => new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(valor));

function CardResumo({ titulo, valor, descricao, icone, destaque = "text-foreground" }: { titulo: string; valor: number; descricao: string; icone: React.ReactNode; destaque?: string }) {
  return <div className="rounded-xl border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{titulo}</p><p className={`mt-2 text-2xl font-bold tabular-nums ${destaque}`}>{valor}</p><p className="mt-1 text-xs text-muted-foreground">{descricao}</p></div><div className="rounded-lg bg-muted p-2.5 text-muted-foreground">{icone}</div></div></div>;
}

export default function RelatorioPlaquetasPage() {
  const [filtros, setFiltros] = useState({ busca: "", situacao: "todas" as "todas" | "duplicada" | "sem_plaqueta", somenteDisponiveis: true });
  const relatorio = trpc.producao.plaquetas.relatorioExcecoes.useQuery(filtros);
  const resumo = relatorio.data?.resumo ?? { duplicadas: 0, semPlaqueta: 0, pendentesConferencia: 0, disponiveis: 0 };
  const itens = relatorio.data?.itens ?? [];

  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-3 border-b pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Estoque de toras</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Relatório de plaquetas</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Acompanhe as plaquetas físicas repetidas e as toras identificadas internamente que exigem regularização.</p></div><Button variant="outline" size="sm" asChild><Link href="/estoque"><ArrowLeft className="mr-1.5 h-4 w-4" />Voltar ao estoque</Link></Button></header>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><CardResumo titulo="Plaquetas duplicadas" valor={resumo.duplicadas} descricao="Registros com código físico repetido" icone={<FileWarning className="h-5 w-5" />} destaque="text-amber-700" /><CardResumo titulo="Sem plaqueta física" valor={resumo.semPlaqueta} descricao="Toras com identificação interna" icone={<TreePine className="h-5 w-5" />} destaque="text-sky-700" /><CardResumo titulo="Pendentes de conferência" valor={resumo.pendentesConferencia} descricao="Duplicadas ainda disponíveis" icone={<ClipboardCheck className="h-5 w-5" />} destaque="text-rose-700" /><CardResumo titulo="Exceções disponíveis" valor={resumo.disponiveis} descricao="Prontas para regularização" icone={<AlertTriangle className="h-5 w-5" />} /></div>

    <section className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="flex flex-col gap-3 border-b bg-muted/20 px-5 py-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="font-semibold">Ocorrências de identificação</h2><p className="mt-0.5 text-xs text-muted-foreground">A primeira ocorrência usa o código físico; as seguintes recebem um sobrescrito, como <strong>22²</strong>.</p></div><div className="grid w-full gap-2 sm:grid-cols-[minmax(0,1fr)_180px_auto] lg:max-w-2xl"><div className="relative"><Search className="pointer-events-none absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" /><Input aria-label="Pesquisar no relatório de plaquetas" className="pl-8" value={filtros.busca} onChange={(evento) => setFiltros((atual) => ({ ...atual, busca: evento.target.value }))} placeholder="Plaqueta, ID interno ou essência" /></div><select aria-label="Filtrar tipo de ocorrência" className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={filtros.situacao} onChange={(evento) => setFiltros((atual) => ({ ...atual, situacao: evento.target.value as typeof atual.situacao }))}><option value="todas">Todas as ocorrências</option><option value="duplicada">Duplicadas</option><option value="sem_plaqueta">Sem plaqueta</option></select><label className="flex h-9 items-center gap-2 whitespace-nowrap px-1 text-xs text-muted-foreground"><input type="checkbox" className="h-4 w-4 accent-primary" checked={filtros.somenteDisponiveis} onChange={(evento) => setFiltros((atual) => ({ ...atual, somenteDisponiveis: evento.target.checked }))} />Somente disponíveis</label></div></div>
      {relatorio.isLoading ? <div className="p-10 text-center text-sm text-muted-foreground">Carregando ocorrências…</div> : itens.length ? <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Identificação</TableHead><TableHead>Essência</TableHead><TableHead className="text-right">Diâmetro</TableHead><TableHead className="text-right">Comprimento</TableHead><TableHead className="text-right">Volume</TableHead><TableHead>Ocorrência</TableHead><TableHead>Estado</TableHead><TableHead>Entrada</TableHead></TableRow></TableHeader><TableBody>{itens.map((item: any) => <TableRow key={item.id}><TableCell><p className="font-semibold">{etiquetaPlaqueta(item)}</p><p className="font-mono text-[10px] text-muted-foreground">ID: {item.codigo}</p></TableCell><TableCell>{item.madeiraNome}</TableCell><TableCell className="text-right">{item.diametro ? `${formatarNumero(item.diametro, 2)} cm` : "—"}</TableCell><TableCell className="text-right">{item.comprimento ? `${formatarNumero(item.comprimento, 2)} m` : "—"}</TableCell><TableCell className="text-right">{formatarNumero(item.volumeDisponivel)} m³</TableCell><TableCell>{item.situacaoIdentificacao === "duplicada" ? <Badge variant="outline" className="border-amber-300 bg-amber-50 text-amber-900">Duplicada {item.totalDuplicidades > 1 ? `(${item.indiceDuplicidade}/${item.totalDuplicidades})` : ""}</Badge> : <Badge variant="outline" className="border-sky-300 bg-sky-50 text-sky-900">Sem plaqueta física</Badge>}</TableCell><TableCell>{item.estado === "disponivel" ? <Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">Disponível</Badge> : <Badge variant="outline" className="bg-muted text-muted-foreground">{item.estado}</Badge>}</TableCell><TableCell>{formatarData(item.createdAt)}</TableCell></TableRow>)}</TableBody></Table></div> : <div className="p-10 text-center"><FileWarning className="mx-auto h-8 w-8 text-muted-foreground" /><p className="mt-3 text-sm font-medium">Nenhuma ocorrência encontrada</p><p className="mt-1 text-xs text-muted-foreground">Ajuste os filtros ou desmarque a opção de exibir apenas toras disponíveis.</p></div>}</section>
  </div>;
}
